apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - librespeed/ks.yaml
  - media
  - flaresolverr/ks.yaml
  - vaultwarden/ks.yaml
  - papermerge/ks.yaml
  - homepage/ks.yaml
  - nextcloud/ks.yaml
  - external-service
  - odoo/ks.yaml
  - grafana/ks.yaml
  - prometheus/ks.yaml
