apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - media
  - flaresolverr/ks.yaml
  - vaultwarden/ks.yaml
  - homepage/ks.yaml
  - nextcloud/ks.yaml
  - external-service
  - grafana/ks.yaml
  - unpoller/ks.yaml
  - immich/ks.yaml
#  - grocy/ks.yamls
  - manyfold/ks.yaml