apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:c1lFYe18CNRTBy9FcGsIm+cIKilgm+EF5k/PjjHJPhZS32q+ZgTmNFAbA6GB3z4sfEProWIMuHDp+Xcwu1ZaxIa9zvoG3m0RB2u5HjEXUbM9uTGqDhXF44sy3kTOTSlGM2e4ZFN4sbPYP0qdLlgSPn0lW1ePUucWSoK3fKF2YXWomYwOTNHglK/4H2LSQN7EY6ZqLWPKxD8R23eOw6KG9xV3rptmVB7P36hAnlDi/oP8AlYxZD6DwrVap03iogmdQqIvP4+fSDsyYiZcwbenmNds/2uVkRYxG2myfLx6Hm8tVqzyG40QltKsuDHw0PCFAX5fqQ0GgN9YASaLzTXXPGGefvQgS/nbeFasRYgy3kx7EFpLQl+1iN3cnm3iUDLB,iv:EnFk7k4bQQVIdlYZIVb01yo9ELgJyPn4PH/Ltcs46nk=,tag:oK740E75tGJou41d8la3bQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:lQVsQM0Osp610Y7P9KJioaAfCUSWBS0pamSLQJnrD8jKcwkW1pX3T3sZBFwBIhrvfbAOWyNdNqfJDGilZAeOGmB34q3kK/Ziu8M/Rior/smMhELBcbap5mBVXlR51oCwp45yzpmKkWGMq/IeaYqNHNZTuXVbYErZg3b1beXrIYzBW95zTLtskMaBYNi06pZNlBnH2LPhGDliIL6soScOkpTyBUQB3Q/Jm8ReNgUV3TTUc4hTnNkcyctu7BxWB+xTm+XDxDAgyYwoKWA+XA==,iv:oWPPo3f8/f95OOld4Fyn2l51bwTZptauBIhrF18B82Q=,tag:K2w04+X+rrvk+DHhUO1sfg==,type:str]
    known_hosts: ENC[AES256_GCM,data:hIwAg80fKDXf9vemhkKvwjX7sKNHIJCuFAQkC99kzAMRA/QDTHWsvPjxXwsbXZlRTJedHeAwet43CFKq7Mgrq6iC5rNWhmNZjsGSmZqwNxNTKGcCKGpdqyegHDyC85uH0Nr23WYA2rHI79YtXKHp82oNCuEL3iGsDHmLF5JnBBzTYEsYyxE1vrmu0qMKRZCdOQTyZtEuAn1Ba8eqcIShoF3dKGunpDbHj/E8,iv:cPCCwqgrlMx1VW8msoWUnwAH2n+vVlNx9sD5GE+M4G0=,tag:45RXU8ZJfKOp53xMdwpSmw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2THRhTjc0OHB3Qkg3QlYr
            ZlBha3ErbktXNndiM0JQV0syWE1TbWV1QkdFClBkY2oxSXFrUWFXWFFnYk5NaG5T
            Z21ob0wxY2VUUnFFTEQ4cVJYWmtiTGsKLS0tIHpmeXl3VmdaYm1LaWJUSStIZzJm
            WjRKOS83MjJ4ZUhONEdlU2RydnlpajAKqTI7bm6RGzYl6lyPEtgvm30hgA0eSRyO
            k0mgwoNMWJDRclu1g90a4DidDuuojpfq18OV4S+dTAZlOmbPWVwnRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T13:43:21Z"
    mac: ENC[AES256_GCM,data:jt03PENlBaPOqvFtuMPDqmuQVZUHHTp8LjuTfK7dAYm/SHZJmbHq0zbllU4KwIVSNivDUI0soSy3pQfzICf0eiiYPS7I8sGaYBxa6Kra+5S75Gt2C30ydBwTWTCvPTl1CnQp1eL3OYFswZ6SASIYNOkK54E5kYI5M7e7l/pG1Vc=,iv:InnqxhcX8VyHtdiHBNhQqE+wDNZhQ0WHqKTWWOHrWf0=,tag:E6PBH+brOENIMkYPryaSnQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
