apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hl42F0+kIr2z/tG5vTEgR28fKaOavlwg6D/Tq+NCkXxXh3xjFqv7SxTo0h6ZvtQdbQlwySTztodypmnv/5jrvjQWyoV6qL4EP5LYfcjEdfv45VCsQAjHGsXvVfLxpJYkxLAocHEVQG3GWZZrTxUwLzj8J88QG++5TBPJ+lU5hyqaZvNgwBzWzoD+x+nqVzhJkp5NKSrJ9VRlTE9nWvhM7J6IsGHTA4SGBfxpH0vg/4yWdTAMwJgkLVdzh68CqMKCSv+WPEo9Q9kDXJbPJs1qereDsYJEVISHoi3YjtaFkOW30U8LsouvHm/8GSnCcR5Hd98hFSc1ZQSk/UIsCo6s1kn7WgciqU8ZIlhXMyQPv6/AHQx6UAE+lYmMmIZdON7A,iv:+TMqlg0uTwUdDbl5Z72VdI+HlaHnlyrdCYIGoD1MvfE=,tag:RLgHK4orqJg2Wrb2dvCkZQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:iaS9kpFOvxS+RrkuPYawg54oRxQtmIxfcmo9sI4CWdraxR9NexiGXbZG/h61+CSZO053FVsepHYE2vZh+dwHsiK0cbduC8OSvedGJEH6z+OtKPKwQtGPFGtvoUIvTVScINgY1TZnz/BrfWKCPsQOXRoZ0rP49Jwcaw13RVHvCpFfgtpZFz6orUV5hrNQRUOG8ylWlCwUfgGHDy3btyMAl9wJRiosqCAdu0qoLwJ7y6JWEj3UOtaQAKGfVWnHpL1pLeDUgBFYWYUCUSnn5g==,iv:/J23ChoAppRo+5R+vhrKEP5TlsiNHIKRU0n4jAKzTHE=,tag:Ps4YcmiT9JVQvoEQTXa8cw==,type:str]
    known_hosts: ENC[AES256_GCM,data:WvkH9GGe9+gGmJF6C3xSsc53y9UUaegj5PgOMUDbEXb7jUVt0UBdAJCzYVvuvr8/xX2oSNtUUtSASeLHtlLm2FlYc2M3RzmI643Z3flE/0cOUl87kAn/rPXYX6amtBftxhBxoJsVq+GxJYyejs8y79DpGXJMqWuo4YOO7yPVOG33OildaJDGN3SKHOtcpHbyInJcRzl1b7CEQwMZJeJfgC/fEBAlzeMqveRm,iv:hHhDzeZRRLte2p+69rQm9dEeHf7Oe/ONgL7Mg+ztBDA=,tag:4y7a9jzsnnLiBeW1H28blQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NUhNY3lKa0RTbGVoNFdJ
            dVBrb0hzTFYxTnVYaWxNcGdIc1F0ZTAydXdZCkc0SWo1MS9DaUN4UTNKN3E1czZs
            RVRCc3RQa1h3UGxFOVBOKzBUcEx1TVkKLS0tIE1QOVFORWdoUG5LaUJlc0JoNUFQ
            a3BrVFZtSkNYbjNCWXd0U2dlRWdTTmMK1dr+eRc0AFgYnD3pvN16FtPvIuX62V60
            KEA6aAp0exuWprkdUvbXhxXLmsYUeqjETMOjrUvLxVFOLVLOSyMcUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T18:28:50Z"
    mac: ENC[AES256_GCM,data:xhzlOfW0v0WF913iuEv/c/5oWJb5HjWeuILYGssYHXJe9PoKkkA3QdiP/MTaazEUf0wzjNB5Y74Ea8qa4ZbIOvhlMo70gLQQbUgF6VNRSK1O7ugL0KGiRhi/59jB9M7lw9BOKefNkK+UFY+j604abzG3CGKRGltx5qjKqaIGFWU=,iv:BQN2V/XNpR3NOnotCkrRslIsMWag7oKdH3Ade9Tpmts=,tag:9YPVuewE/5XIzsO0vAgltA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
