apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:u1MwfEq8AnOcrCGN+TsHR2x3/gGz1OhYK65Q48IqFPxELRDhhwDEIV1k2xfuE/ggZ8JztXiqAd0RTr6h+ZCbJvYb4yI8s3waOt7AoEpyl/Xk85ywvHSnOyNzho/L4p4s+1TfGhm2JGdTaalgEkPzzTy32xIYd3q9/4M1SU38uOILRViP37EuezdhkBsP9phnVmsYoXq/loIFg/jev9a+2T2p3KT72KWtHzwJrd5R9xcOz5S0x9tGQTTqjsrL3kv5VzHEMQ1Gz1jGRWkYC0EfAOGh7pmFbaRiSoQcWNFjmY26rlZoLQMArm1EX2rU7QHSzzLmGrE6Qhr3OcRjYnHDNLfhfjQrX6zYclc4eeRNl6Ywx9+McTF4L7UzDG9bt1xH,iv:MT7Bc/aC1WqEAbJ20ZYJHNP44VjiLGzUnbLE9sd4tao=,tag:fhvQILRAINVzXUQ4L18qDg==,type:str]
    identity.pub: ENC[AES256_GCM,data:wiWxzCOcIaxAzd/uJVkO7P7vYh4wuaq3060PeSXLOn0kEBJsm24HJr8d1XpTMAOwJXuzg2QsivtIrKbwnMlFYXKll2efOFY0+9e+p+/XPu4f7DYOh54IAn7YVeJTShaL4+iEhFHXxeTMW25ivc6n+bDTvSUuMkww56iF+vgV0YebNf0Tb/HT1et92SmDlex9C4Edmp07waWjReW+enom/m6gid/CTjD64fo/wE5ElDDI4l5hsmNf207wARZEslbpDiQbhEw3RDFaG36c5A==,iv:qRusXR+5y8KoHWfiTnpzcelepocYIMjbDiOLM5PWR6M=,tag:bWfn8VKvY5nYBEr6cdzrbg==,type:str]
    known_hosts: ENC[AES256_GCM,data:m1CrRzK8v7X7f4/somBuL6i45KhkQZJen+Ai40go8PvtPP/pUfLJ35/CxDE6c6Wn0GsrqEKVhKrnIgpKKdKxA2FJu/35oBPrkJ8ChdrHb1lZWjBcRT3QpLJ8cyZ/Qe8qYbNKwjnMurmoayr3h6QFINgG826/vrnMwSJePoz6AGyBp457uLVoZWDkwhd+BKFqPM2ED5IFaAcGPt43Ib5xuS0MQH0yOMbRaH4Y,iv:Wt8cW49tbCtEOqoHfoV2Z343GjMOlxjRYfQEpl6MBBk=,tag:Fv+5FBHHloKQjT1tymteGw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMzlibWRibFFYREtEQzVI
            VndMbWFzeFhCb2U0TWFGbzR3YURWeURoR3hZClRFWUN3SGRQT0ROaytOYWF2bWNC
            RmVwSkdoUkliT2ZtTEJneG9QQkRXRkEKLS0tIC9BY0o3d3N0UkZjRDh1d3NEN0hZ
            MG5qaGFXcmNTWUNoU2hmTUo1bWlrOW8KEuheg10Ym0lefOzLaxMpmo/BfZT4/Oxt
            NM9+WE3wP4G4D14CuVJU/A9HZXsyxNA89UoQqKqHFIpTGDqVceMSAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T17:46:06Z"
    mac: ENC[AES256_GCM,data:+oF+JEtbNedwyFulrYpFOEogpQKwmTGPcry2/Tzu5mHNTbK3xrloVclhaoRlhqroo+6HpIPJPCGEvJrORb3TYNP/Em+zgo6cTqc3pLf5vZyfk2CrhCtgowLKYkrWfzjenFyfC/H5d//ZOONWOCnd4rCm/k2AJrNH+P+glxAU0pQ=,iv:URdre9q3syH8rFcNhkguUp8vjY4ExVf3eBT7HFV2uxQ=,tag:1kxQ5kj+kjmdlRKjd6Yfqg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
