apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HB0vPJH7gfYknMH4NsDWXa2+1kpBpq4ppyJ3YwLv+viRioeD/xTiAbGD1Jq/KwCUE7ZAIfILVE/DN5d+mS65g7/OvaJYDrBY3Z6AfYl/IRqdI5jTEtzfiuTC9ThT0XqWgNERKi2kOVj62aujzcubonnw1sb6b2TRKeFeBTLmw5mlGQe3kpncL+j/ixQ3jg+8zkjm4djKcQzdKOMaXEywhjjBK3pUSIXBqB28LCrqm4q6KVxsTOF/ITKmiIlMFiU9A+jugcjbNuaUO9blCWRK7fRk9Uo1idRX02FPXmb1L88S4AYpDNZ81AYDSL53xrIEaZdtWAR0yIQ8Q+o64Iq1pBv7LxmGd/ycoQoKszmaZebsYazTbvxHGOyXRCi9+OV5,iv:iFgVIFo2kqVTgQ4tdCnlnRfXc3DLynXDTvWfmOuQYQ0=,tag:rlziljMwwNmr6/ZRKYPEiw==,type:str]
    identity.pub: ENC[AES256_GCM,data:LrXPDgrYjEhkrrpaOJ0QRInNnyzvc+RugxzhpikkUJMEN4jhqsUlwl2aOOmIfZGwY1rw70b/bTDv7AvTLDrBcpe5NEDqov6rdiCaKa+aLnZnlqmTEUY0PwRfzV3syKOm+pa2L4CaEUUpP8YVzq1Ccox+5ee42HFUk9CdncPv1GXoJZMPk/AcQfEfaWLi4jZZxmueq78aYEUOI2AHtcICTwi0gaPEzOdrDnwmdcMfFZzX4EU7wcJGogvN9iQ84o1rphGAMtV5MvaErtJtcw==,iv:n/VG/fcNgMiUAkBcqyYhwT+Ck1SiRodQfxDru0/5qT4=,tag:yhFzvCQwdxhBvARdvL8ljw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZJJNbzs98ODGywZLLQkyRrH2ob2vyn7YT9acPB+aNWxfL6Ua49h2BthP+NAtPJWfR7C70yyBQM8riau+XCUAoDDwRIBWFSY5lAe5E234yCW7GEKQAKPkMeyQChqLH+8k40pf2y0jdQM9MrBXRxulSRcRnBiU12cwGFNbnFSiyer5edaiDst3V4MTSApT93m+1q0s8S+FUmdvF3yUCr/QA/jOTHF6U7+ZDyuq,iv:mtPP8HgWjsvtD3dWmyGuwNgy/Ul2CqxoUmZOfMDYEY8=,tag:XJwzGnJWURwBxesOcwYCTA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeXEyeTQwSHF4a2lkZjIx
            VGZ0WTNFWDhpb1lyQXBCS3dQMDhMRkQ5N1ZnCkVaSEhZTVhNSlZjQ0swdkVCdU5p
            elk5d09BNWtKTHV4Z2VTUHhHUkxZbDQKLS0tIEN1OHIrNjhtci9VS3oxbmVPWk16
            bXdCRi9DRVdqSEZJNzFRejBCQzdsSWcK0bYplfOi2v4jZ4gEIKC1rtcyEN8X93MH
            ldVN+J05XyPKJhY35PZNtQJPdQ5BN5k3arAhAxSP3IT2ZQD40u9qxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T18:56:05Z"
    mac: ENC[AES256_GCM,data:paGTPmtTg4fBWkfx5rukMOY6+7ez0Svg2DYhRqxtZwv+vqCHHXoa/iyJ9PckGsWO00bYHCtqRS+/gfRE5p/v/zD49jzVL9vikniTYH+uguxB+l4Yw6HrdaNvPFcyVh/15Mo9fon4NE9dNZaa3xPFinNjVEAyl3fMVqPS7EbpIA0=,iv:GrSS+dDYmf+qM0OMtZb5aV1bcpNRq7kahjIVxfHbNPk=,tag:+X9As0zJcNdMf+z1rFIuvw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
