apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:H7tj+iUx14F9NpP9CzbLZM3YqPcRue5Sand4wcMavWtQkT6YCkvO940AZYxT/S6PpEsmDwW+AvgNuekICj+sL2t9So+ZR6CItFnFTVVanLupfBKtwszVOzf1kNCPmmpVzk1/ynRl1dkME8eKHp6r82M9JUPIE4ZvMxkIGyAnELdTzR+s1JCQbNP5VOFInvOcfTVRHMyrf3N0hIsbcRCM9RkXb+Bd3SJAGMJv1qwpXDfW5kj0TtoUyzVHmHTUw6wsj7+M3ZOqZTNF1BE6GGRLvRsi+UTEOfkOew8tbZ+HbmySyQJUbEnL0ks1vXCSOP5lerKePG7h4vLFBfiltgA32kEngKYXlvdbaLrsKUOi3szfxCigaotTUkQ/XmJ3W/tT,iv:dGMrDPMOI+jQEKJA6EmxxLTfxVj9npRTMiDuRCXjHGE=,tag:Drn0ROrNgdisV7XN9/Kcxw==,type:str]
    identity.pub: ENC[AES256_GCM,data:RK3TukhZRoINGwE9XU2071jW2DZKl0yddsZ3//aSZACC4SdOMpy/XpD0+1DZCEzmakqLXYp198SK6w/uX/D16wOWgQKsCGa6/xht1tQZilWoCxdfjPEbe/h3H0JVD0KStBPUt988PXj5hY43wRq95JQDIjL9yR7dhpAEc/iNdet6tuUU9jO2JLel1Ed8dFY6mVNSnKriprv+8UoINs75r6b5rzMj9u1ItJbmn24fKqwoxoPkDzTxn1ok5vYFMgSn3DKqfyda+9I+SCqLcQ==,iv:t3vvSqIrm05sAwPBpDO4MMGJl3KQZOimbpM7zr8oPJc=,tag:aAEPDQlyNa4S+KDKWDTApw==,type:str]
    known_hosts: ENC[AES256_GCM,data:BYuKiaOCGNJT4bxnQaBvAW9KXRszXPKj5hCnh1JdMjXUNbSsC074zamVFQjTQOUuNiQ3HInZdl8zpjuCNbSVLbDW3Ew72g2fJgXKL/NUBICYigLUTBu/SL2oat6XYQ22cPJOSl77xGH8q7sZ31dKVP8FkxCB/ZqqT6vMjWcy8HSB+Q3DZ+wKQ2N8+j4kPrLxywYM0QRZfVH9Eprklyo+X5+uyNiAGFqQvn7n,iv:T81QQ7yu9JQtfKyycVfEQLJOAKeOyX6STpts4CU9yow=,tag:6SzJ8BZOJC9Lxj4/VZP4Jg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RHFIT0x4cFVnRFpUUW1l
            VnFJT2crRnE4RURvakZEN0hNU0xCaUp6S1FNClpXWDA2VWNRZXdpOEJDakZHVW8x
            ZUpaRWxPRVZzN1NwSWkwWjlFbWIxRXMKLS0tIEpFWFBKaWJnWmI1SW43eTFna3hr
            YS9sU21HQkNLdnNiSmVFRzEwZThSQ0EK8LCkwOyoHVc+GkwDS5Stw56cskIXjh9n
            Adu5mhftzG3DfXYcRQ4edm0f4MsreKYRqn2HzcO4GkEs02J3Mz0n/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T08:57:43Z"
    mac: ENC[AES256_GCM,data:RapnruwGp7x2mP6fSP35am0UrDurIp+q9mBmp4VMm+kfd+v5uxKWno+zxdFI6IbLy5oTVlISiNY1jjxpvRKfzZ4MEvpSJNJ8xQ66nucltsGfIr2XHiDFr5nWFQsos8eJlZSJdL4xZpusTqa/Pz03QoeaQgPm/8tUWYf7QVxHL7M=,iv:7ubsEquE/RVs/Y5pRGLs6mn/7GhGvoICx70/X3EOvG8=,tag:+xAvoZ4JkAoDiEunvnQ+yA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
