apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:knoQtdEBhe5KdkiVUqLJ4xukd/IoDlC50Ryz184TTBSCQf0gHoku/HrZD/SU9fJ+6vI3ACPBkyW3qs2rT3O4Lyong0L1hV/QBIgbpiV8thCfoByFhAwxNbPyxXXFyhHGO82LgH6/RONWfJQo9yTJH/6yDEtziYCORzpjM+9ssypP4j21OSr2G4Hh9cdfA42XEwh+1a8gHUYPyAqIXtJG7AQccDXtxVArrgBIAT3fzsoot/SwtL+ws6+POEyzuE0OWQIUqnTHa3qsYkNQ7n0RfCVFxptMRKPuUbf8JQMaBeP50ANpvXOK0Ej4EZaGBSOPAHFjBjiOrWwJ5E04UnewAyYQUj7sbrpq2k3cFtFmLT/Kot5GTs8GF8+2iI5WDJ5E,iv:NPVOq5veJ9mgUV1kuhZNkKsjwYTi3x/jkEFltuoJ0y4=,tag:AEniHJWhkcdjPBCadOaqNg==,type:str]
    identity.pub: ENC[AES256_GCM,data:raog6suo1mUJr4Vk+aWjBjbtWU7mqC+vZFYAwSHm8CzFv2TR8sC5Dn80LAhM+//gk9j/z4fXtc6LD9KRz4A/3mahkgV5KrzMRisTt/Dt+v7iKMC/SF937V34Za1lTAfuCfiI9VN/ssBdCxROSsGh7F/NzD9HwejEhuQZeKOsjxf9Fe8SlDj4LOR7vYPOw/czakxtoKYkYWfcASae/M58q6rfO8Z5R1Gt7IsMglhISVNH6id094v3QI0VrygE1oyXAevX/K2Kfml1TL9ipQ==,iv:4oOTM0gSE9Q4D1nA/pIsjt5VIy3ks3spv5xS+SA4DjM=,tag:JAQdzFChY++nPsP9Vk+5KA==,type:str]
    known_hosts: ENC[AES256_GCM,data:zGjJjdVu/MDLkQszOk+4Vz7f4bhFuEPVSqKS7aL3f4tQRpVYuUzHrN1iYG0LZds/d13Na5PkFALC/u+4btIvtaTpawEk0ffL+leHwdtKDa4ek1gk360tTm3HjRwmPq4j0eyJA/DX8qUYEwPYgOHE2SEcYOYTh+Go7lo85SmhPwknQoF57ziOZOQNnH1hMaoElqfcDQbSDYvEFOwa5YAa2nLm1DpnWh2CiwI2,iv:vzfX9+TCNZGVp0dDqasq4fARVch9P9Ei5T1jdel92h8=,tag:+l5bv1RkExt87HdrCXcArA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOCtsK2d2RkFadFFmWWN1
            TkdJZ3RxeVpWRm9aQXhJUzkxalhwWTJKV1FZClFmQWhKRnZ4WDBmYkl3R2ZvaGYr
            bjMxWTZkeVlwZVByb0lRUXVnNmtSNXMKLS0tIFNCbi9qb0EvV1JyRytIWHpaVUJC
            ZHgvbFU1ak9iQzZoSjA3Wk05cG10czQKyM/WosaD9uFwLxpqH6RGg8NMrgAipHx8
            QehiDNlqO0nn794fmJ2P/cpg6as6WfTz6gsXEOcOWngtuGfxcqwWDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-20T18:24:05Z"
    mac: ENC[AES256_GCM,data:6rHstJDVj6DLrwzkWsXJN8KbsYxtGmpg6N4GVaLXvKJ2ZlIwayIGvcfw8qS+H8kODaV8sVCZPNeRzuhXGUo3yADYlsB7mDB7B1nNDweXr1Ogzi90h+XrrJrox8kpeaBXikUkRrMplx3ZKCBS0EqnklWPmknMo5+hJWq3DHx7m8U=,iv:+A+UzRkuJJEtGUteGHlN+ba34eSuYduzg/HwJmHST30=,tag:Cfzza7TuY/KGazc/p8Mpkw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
