apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Rzh8sLpW8YwGZbu5u/UBX2IxpIgbvWZQmEyp0t1vtaOmLagcrO7AVo3hXq0WnEC4Zy1nvhnDGaIokUP1vINnTWfS/2kZvBhh+Iy8h4MWtLLOoDWEQKL4wE5SHUTI0Sucpop4iKum2sUfKmSW8L+1nN7JiRAP+Imhdnnka+GhoAiC9CeiZZPyfQW49+PdkgtvOYve6gmGpmWncN9akKWOfWHK8oKm506BxYAd04v1XTDDud09yVRQ5X0DHvxlFSw3zbLh5LjnMwnCnMQibgFHqAQU1U/BLAU97pbobuOsbPMakPEd62AKQJ5WtStcAObrDPJ2FlGuq2UY54BzmzKhQx53GGLC1hIyh8kVgXu+cj1+Yn1wU+RWDwYXkLQUkXqA,iv:BqPiRUnB+vxSXQ65ggZ5uXSPgNyn4YCEVnC1ELN4eU8=,tag:QsB7nB29XZotVszCLtO2zA==,type:str]
    identity.pub: ENC[AES256_GCM,data:0h9Iq5R1xUzY/cQZtvvo2aPzy17gUKG6pFHqk87rqUNTe3COaGJ+bxOnL1/aGoFlBvVSatUXjXuTzU7KeX5RIcujzTGDhCHIwq2CvBgxZbJnESSgrQWaO6bPBkHj9YBn7eNbSvdBS+LmG9P01dhkjDUGFqUIZ0pvVm4NuJR1c+xFj8vt0oN2XAnTpgZNl4gjOMhi+P1aPxBDn8OkjdkcY0Y5Oe1Q+tuNlmXV/SN7WLQayEB/qcnZ/mxbwa/tCvdQUXPdv3mygOa40hD8Eg==,iv:mCAckvHtMyP+HO5CwUovWmImDUm6r6IkssgJn1su44w=,tag:cpFNoXAqGrN0itc/kQFwig==,type:str]
    known_hosts: ENC[AES256_GCM,data:Rg6eqtGO3U2QLUvU+BHXOpt+LMeiuE1zzvI5mS1LSIC8piCaVTe51RQRlm8XKsVAjTU8nAY5k7p0RfPAAu5flXuHh7Xh60R3fKZzpY2rRaxH5cIfwU2lr1t7/igmDrKQrKr80w31qLdp+NmkYXuTwmrdLNg0PNZW7eQPCigGeApg4kIN0Zf6EvQ2c5922wbsGLNACvKRo0oPgp1JSrEMCU2BY2+1DBcjXzL8,iv:orSfkPWxub4iugU9R53ts8e1wJBQ93/U92g33qNVY0w=,tag:MsWkg4nz3jDY8m7uWbPvGw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1trupqumxaasr8zrpj6665q55gn2gk5vxars2lglskutauyfvgyvq8yapef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYUxMQ3d0NmVIaVBXeWln
            MWlZN3ZKaWpnbkd3TGtHb0ROMml3bC91bDFJCjAzL1Jha2E4cTQ0eVpPcEhjamZJ
            TGNmSHlFWlAzbjRtNFUrZ3MvT0NrZ00KLS0tIFFsSk9SS1FwTmkyeGE4RmNobk5R
            WDBka2J2ZzBrN3BtV2tqM3UzNlpZbmMKVPKZdXF3sqF0bpsLsnxAUYJLUtdhmyz+
            Bhn+lQOq20sMkDskse4St6lYDb/RlKpNeO05/nFFfUOG6c+8JhqXlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T09:11:27Z"
    mac: ENC[AES256_GCM,data:0NdxTvp661Z+zEk7SwJFdSEW2ahEagN3llchJ6bUmUl2M8JthmCoZeBUmDpbw4p5qZlmUWL9fN1JuSZBUMEZhJzHjVRfVRkQv760Y+hmM9/ODpmwYVxdmyoV3rrM3kwICFbUMp/2bfq997/npYTCrjQ+irr2pzMIr1C2DvXQSbE=,iv:wrfdfFBDWpQ2B+UPRop0MyUnnA8NAui1qtMkBciTNcg=,tag:YxQCKCEAy/a4/+wi4AKg+A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
